# This is a basic workflow to help you get started with Actions

name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
      - uses: NWBY/pest-action@v1.1.1
